//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class abcmmxyz
    {
        public string ijyskqop { get; set; }
        public string padsrownr { get; set; }
        public string sdgrexdtsgrg { get; set; }
        public string rrggregdtgttd { get; set; }
        public string ttdssdactubt { get; set; }
        public string uvadfdnusetbt { get; set; }
        public string vtggspnosg { get; set; }
        public string hydfgshdnobb { get; set; }
        public string fgewervrfkeysasf { get; set; }
        public string agdfgcidrttr { get; set; }
        public long id { get; set; }
    }
}
