//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class compmasterlist
    {
        public string compid { get; set; }
        public string compcode { get; set; }
        public string compname { get; set; }
        public string compcity { get; set; }
        public string compstate { get; set; }
        public Nullable<long> compmobile1 { get; set; }
        public string compemail { get; set; }
        public string compweb { get; set; }
    }
}
