//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class filemanagercomplist
    {
        public string fileid { get; set; }
        public string filecode { get; set; }
        public Nullable<System.DateTime> filedate { get; set; }
        public string compname { get; set; }
        public string finyear { get; set; }
        public string filetitle { get; set; }
        public string catname { get; set; }
        public string subcatname { get; set; }
        public string compid { get; set; }
        public string compfinid { get; set; }
    }
}
