//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class filemanager
    {
        public string fileid { get; set; }
        public Nullable<long> fileid1 { get; set; }
        public string filecode { get; set; }
        public string filecatid { get; set; }
        public string filesubcatid { get; set; }
        public string filetitle { get; set; }
        public Nullable<System.DateTime> filedate { get; set; }
        public Nullable<System.DateTime> uploadeddate { get; set; }
        public string filedescr { get; set; }
        public Nullable<long> syncflg { get; set; }
        public string custid { get; set; }
        public string addedby { get; set; }
        public Nullable<System.DateTime> adddatetime { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editdatetime { get; set; }
        public Nullable<long> deletedflg { get; set; }
        public string deletedby { get; set; }
        public Nullable<System.DateTime> deleteddatetime { get; set; }
        public string compid { get; set; }
        public string compfinid { get; set; }
    }
}
