//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstfilesubcategory
    {
        public long subcatid { get; set; }
        public Nullable<long> catid { get; set; }
        public Nullable<long> storeindb { get; set; }
        public string subcatname { get; set; }
        public string custid { get; set; }
    }
}
