//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermasterlist
    {
        public string userid { get; set; }
        public string username { get; set; }
        public string usermobile { get; set; }
        public string useremail { get; set; }
        public string userstatus { get; set; }
    }
}
