//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfolist
    {
        public long infoid { get; set; }
        public string compcode { get; set; }
        public string compname { get; set; }
        public string compaddr1 { get; set; }
        public string compaddr2 { get; set; }
        public string compaddr3 { get; set; }
        public string compcity { get; set; }
        public Nullable<long> compzip { get; set; }
        public string compstate { get; set; }
        public Nullable<long> compstatecode { get; set; }
        public string compcontry { get; set; }
        public Nullable<long> compstdcode { get; set; }
        public Nullable<long> compphone { get; set; }
        public Nullable<long> compmobile1 { get; set; }
        public Nullable<long> compmobile2 { get; set; }
        public string compemail { get; set; }
        public string compweb { get; set; }
        public string compgstno { get; set; }
        public string comppanno { get; set; }
        public string compdruglicno { get; set; }
    }
}
