//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class usermaster
    {
        public string userid { get; set; }
        public Nullable<long> userid1 { get; set; }
        public string username { get; set; }
        public string userpwd { get; set; }
        public string usermobile { get; set; }
        public string useremail { get; set; }
        public string userstatus { get; set; }
        public Nullable<long> syncflg { get; set; }
        public string macid { get; set; }
        public string lockuser { get; set; }
        public Nullable<bool> addrights { get; set; }
        public Nullable<bool> editrights { get; set; }
        public Nullable<bool> deleterights { get; set; }
        public Nullable<bool> uploadrights { get; set; }
        public Nullable<bool> downloadrights { get; set; }
        public Nullable<bool> sendmailrights { get; set; }
        public string custid { get; set; }
    }
}
