//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class compuserright
    {
        public string rightsid { get; set; }
        public Nullable<long> rightsid1 { get; set; }
        public string userid { get; set; }
        public string compid { get; set; }
        public Nullable<bool> compaccess { get; set; }
        public string custid { get; set; }
    }
}
