//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailsetting
    {
        public string id { get; set; }
        public Nullable<long> id1 { get; set; }
        public string portalname { get; set; }
        public string smtpname { get; set; }
        public string enablessl { get; set; }
        public Nullable<long> portno { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public Nullable<long> syncflg { get; set; }
        public string custid { get; set; }
    }
}
