//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstchallandown
    {
        public long id { get; set; }
        public string challanno { get; set; }
        public string filename { get; set; }
        public byte[] fileimage { get; set; }
        public string filetype { get; set; }
    }
}
