//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlog
    {
        public string userlogid { get; set; }
        public Nullable<long> userlogid1 { get; set; }
        public Nullable<System.DateTime> logindate { get; set; }
        public Nullable<System.DateTime> logindatetime { get; set; }
        public Nullable<System.DateTime> logoutdatetime { get; set; }
        public string macid { get; set; }
        public string machinename { get; set; }
        public Nullable<bool> activeflg { get; set; }
        public string userid { get; set; }
        public string custid { get; set; }
    }
}
